# AI-Body 企业微信智能机器人配置文件
app:
  name: "ai-body-wecom-bot"
  version: "1.0.0"
  port: 8080

  # 日志配置
  logging:
    level: "info"    # debug, info, warn, error
    format: "json"   # json, text

# 企业微信机器人配置
wecom_bot:
  # 企业微信应用信息
  corp_id: "${WECOM_CORP_ID}"
  agent_id: "${WECOM_AGENT_ID}"
  
  # 回调验证配置
  token: "${WECOM_BOT_TOKEN}"
  encoding_aes_key: "${WECOM_BOT_ENCODING_AES_KEY}"
  
  # 回调URL配置
  callback_url: "/wecom/callback"
  
  # 消息配置
  max_message_length: 2000
  response_timeout: 30  # 响应超时时间(秒)

# 会话管理配置
session:
  max_sessions: 1000
  session_ttl: "24h"
  max_messages_per_session: 100
  
  # 会话清理配置
  cleanup_interval: "1h"
  inactive_threshold: "2h"